import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

// Builds a Tailwind color scale that reads from CSS custom properties
// (defined per-theme in resources/css/themes.css) instead of static hex,
// so the same utility classes (e.g. `bg-primary-500`) resolve differently
// depending on the `data-theme` attribute on <html>. The `<alpha-value>`
// placeholder keeps opacity modifiers working (e.g. `bg-primary-500/50`).
const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
function cssVarScale(name) {
    return Object.fromEntries(
        SHADES.map((shade) => [shade, `rgb(var(--color-${name}-${shade}) / <alpha-value>)`]),
    );
}

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                heading: ['Manrope', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                // Brand — electric blue-violet. Main actions + brand identity.
                // All 9 scales below read from CSS custom properties defined per
                // theme in resources/css/themes.css (generated by
                // resources/css/generate-themes.mjs) so `data-theme` on <html>
                // switches every one of these classes at once. The comments here
                // describe the light-warm (default) theme's character; other
                // themes vary lightness/neutral hue while keeping the same brand
                // hues (see generate-themes.mjs for the per-theme transforms).
                primary: cssVarScale('primary'),
                // Warm coral — used sparingly for secondary emphasis/accents.
                secondary: cssVarScale('secondary'),
                // Fresh mint — positive states, discovery, subtle highlights.
                accent: cssVarScale('accent'),
                success: cssVarScale('success'),
                warning: cssVarScale('warning'),
                danger: cssVarScale('danger'),
                info: cssVarScale('info'),
                // Warm neutrals — backgrounds, surfaces, borders (never cold gray).
                warm: cssVarScale('warm'),
                // Ink — text colors, charcoal/navy undertone (never pure black).
                ink: cssVarScale('ink'),
                // Card/panel background — lighter than the page bg (`warm-100`)
                // in every theme, including dark ones, so cards still read as
                // "elevated". Replaces literal `bg-white` on surfaces.
                surface: 'rgb(var(--color-surface) / <alpha-value>)',
            },
            borderRadius: {
                lg: '12px',
                xl: '16px',
                '2xl': '20px',
            },
            boxShadow: {
                soft: '0 1px 2px 0 rgb(var(--shadow-tint) / 0.04), 0 1px 3px 0 rgb(var(--shadow-tint) / 0.06)',
                elevated: '0 4px 12px -2px rgb(var(--shadow-tint) / 0.08), 0 2px 6px -2px rgb(var(--shadow-tint) / 0.06)',
            },
        },
    },

    plugins: [forms],
};
