<?php

declare(strict_types=1);

return [
    /*
     * The complete set of color schemes selectable from Profile settings.
     * Every place that needs to validate or list supported schemes (user
     * color_scheme, the theme picker) should read from this single source
     * of truth. Keys match the `data-theme` values defined in
     * resources/css/themes.css (generated by resources/css/generate-themes.mjs).
     */
    'supported' => ['light-warm', 'light-cool', 'light-soft', 'dark-warm', 'dark-cool'],

    'default' => 'light-warm',

    /*
     * Display labels are localized (lang profile.php files,
     * `color_scheme_<key-with-underscores>`) rather than kept here, since
     * unlike a language's native_names these are ordinary UI strings.
     */
    'is_dark' => [
        'light-warm' => false,
        'light-cool' => false,
        'light-soft' => false,
        'dark-warm' => true,
        'dark-cool' => true,
    ],
];
